### ISSUE TITLE
Add some indication of when images were captured

### ISSUE THREAD

**Issue by ihellman** [kaitlynstrickfaden/camTS#10]
Some indication on the plot (I suppose it could be a separate plot) showing where we have images.  We spoke of a rug plot.

**Comment by kaitlynvega** [comment]
Thanks, missed adding that issue earlier. The rug plot might be too busy if we indicate when all photos were taken (we know one will happen every hour), so I might just have the rug plot display the motion-trigger photos unless you're really concerned about camera failures.
